// api/index.js
const express = require('express');
const { html } = require('satori-html');
const satori = require('satori');
const sharp = require('sharp');
const fetch = require('node-fetch');
const fs = require('fs');
const path = require('path');

const app = express();
app.use(express.json()); // To read POST request bodies

// Font path - ensure 'inter.ttf' is in your 'public' folder
// and vercel.json includes it in the build.
const fontPath = path.join(process.cwd(), 'public', 'inter.ttf');
let fontData;
try {
    fontData = fs.readFileSync(fontPath);
} catch (error) {
    console.error("Error loading font from:", fontPath, error);
    // Fallback: If font is not found, Satori might use a default or error.
    // Ensure your Vercel build includes 'public/inter.ttf'.
    fontData = undefined;
}

const FARCASTER_ID = 'aminphantom.eth';
const FARCASTER_PROFILE_URL = `https://warpcast.com/${FARCASTER_ID}`;
// VERCEL_URL is set by Vercel, otherwise use localhost for local dev
const APP_URL = process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'http://localhost:3000';

// --- Helper Functions ---

// Function to generate image with text
async function generateImage(text, error = false) {
    const template = html(`
    <div style="display: flex; flex-direction: column; width: 600px; height: 315px; background-color: ${error ? '#ffebee' : '#e3f2fd'}; color: ${error ? '#c62828' : '#0d47a1'}; padding: 30px; justify-content: center; align-items: center; text-align: center; border: 5px solid ${error ? '#c62828' : '#0d47a1'}; font-size: 24px; line-height: 1.5;">
      <p>${text}</p>
    </div>
  `);

    const svg = await satori(template, {
        width: 600,
        height: 315,
        fonts: fontData ? [{
            name: 'Inter', // Should match the font name if it has one
            data: fontData,
            weight: 400,
            style: 'normal',
        }] : [], // Satori will use its default font if fontData is not available
    });

    return sharp(Buffer.from(svg)).png().toBuffer();
}

// Function to get summary from Wikipedia
async function getWikipediaSummary(searchTerm) {
    if (!searchTerm || searchTerm.trim() === "") {
        return "Please enter a search term.";
    }
    // Use English Wikipedia API
    const WIKIPEDIA_API_URL = `https://en.wikipedia.org/w/api.php?action=query&format=json&prop=extracts&exintro=true&explaintext=true&redirects=1&titles=${encodeURIComponent(searchTerm)}`;
    try {
        const response = await fetch(WIKIPEDIA_API_URL);
        if (!response.ok) {
            console.error(`Wikipedia API request failed with status: ${response.status}`);
            return `Error fetching data: ${response.statusText}`;
        }
        const data = await response.json();
        const pages = data.query.pages;
        const pageId = Object.keys(pages)[0];

        if (pageId === "-1" || !pages[pageId].extract) {
            return `Sorry, no results found for "${searchTerm}".`;
        }

        let summary = pages[pageId].extract;
        // Summarize to about two sentences
        const sentences = summary.split('. ').filter(s => s.trim() !== "");
        
        summary = sentences.slice(0, 2).join('. ') + (sentences.length > 1 ? '.' : '');
        if (summary.length > 250) { // Limit length for better display in image
            summary = summary.substring(0, 247) + "...";
        }
        return summary;
    } catch (error) {
        console.error("Wikipedia API Error:", error);
        return "Error connecting to Wikipedia or processing data.";
    }
}

// --- App Routes ---

// Main route for the frame logic (handles POST requests from Farcaster)
app.post('/api', async (req, res) => {
    const frameMessage = req.body;
    let searchText = "";
    let action = "initial"; // 'initial', 'search'

    if (frameMessage && frameMessage.untrustedData) {
        searchText = frameMessage.untrustedData.inputText || "";
        // Button 1 is for search (buttonIndex is 1-based)
        if (frameMessage.untrustedData.buttonIndex === 1 && searchText.trim() !== "") {
            action = "search";
        }
    }

    let imageUrl;
    let responseText;

    if (action === "search") {
        responseText = await getWikipediaSummary(searchText);
        const isError = responseText.startsWith("Error") || responseText.startsWith("Sorry") || responseText.startsWith("Please");
        // The image URL will be dynamically generated by the /api/image route
        imageUrl = `${APP_URL}/api/image?text=${encodeURIComponent(responseText)}&error=${isError}`;
    } else {
        // Initial frame or when search text is empty
        responseText = "Search for anything!";
        // For the initial state, or if the user clears the input and clicks search without text
        imageUrl = `${APP_URL}/api/image?text=${encodeURIComponent(responseText)}`;
    }

    // Construct the HTML response with Farcaster frame meta tags
    const htmlResponse = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charSet="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta property="og:title" content="SearchCast-01" />
      <meta property="og:image" content="${imageUrl}" />
      <meta property="fc:frame" content="vNext" />
      <meta property="fc:frame:image" content="${imageUrl}" />
      <meta property="fc:frame:image:aspect_ratio" content="1.91:1" />
      <meta property="fc:frame:input:text" content="Enter search term..." />
      <meta property="fc:frame:button:1" content="Search 🔍" />
      <meta property="fc:frame:button:1:action" content="post" /> 
      <meta property="fc:frame:button:2" content="Profile: ${FARCASTER_ID}" />
      <meta property="fc:frame:button:2:action" content="link" />
      <meta property="fc:frame:button:2:target" content="${FARCASTER_PROFILE_URL}" />
      <meta property="fc:frame:post_url" content="${APP_URL}/api" />
    </head>
    <body>
      <h1>SearchCast-01 Frame</h1>
      <p>This is a Farcaster Frame. View it in a Farcaster client or validator.</p>
      <p>Debug - Current search: ${searchText || 'None'}</p>
      <p>Debug - Result: ${action === 'search' ? responseText : 'Awaiting search...'}</p>
      <img src="${imageUrl}" alt="Frame Image" width="600" height="315" />
    </body>
    </html>
    `;
    res.setHeader('Content-Type', 'text/html');
    res.status(200).send(htmlResponse);
});

// Route for serving the dynamically generated image for the frame
app.get('/api/image', async (req, res) => {
    const { text, error } = req.query;
    try {
        const imageBuffer = await generateImage(decodeURIComponent(text || "SearchCast"), error === 'true');
        res.setHeader('Content-Type', 'image/png');
        res.setHeader('Cache-Control', 'public, max-age=3600'); // Cache image for 1 hour
        res.send(imageBuffer);
    } catch (e) {
        console.error("Image generation error:", e);
        // Fallback image if generation fails
        const fallbackIconPath = path.join(process.cwd(), 'public', 'icon.png');
        if (fs.existsSync(fallbackIconPath)) {
            res.sendFile(fallbackIconPath);
        } else {
            res.status(500).send("Error generating image and fallback icon not found.");
        }
    }
});

// Route for the initial frame display (when accessing the root URL via GET)
// This is what users see if they open the URL directly in a browser or for the first Farcaster load.
app.get('/', (req, res) => {
    // The initial image for the frame. Vercel serves files from 'public' at the root.
    // So, 'public/icon.png' is accessible via '[YOUR_APP_URL]/icon.png'
    const initialImageUrl = `${APP_URL}/icon.png`; // Corrected path

    const htmlResponse = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charSet="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>SearchCast-01 Frame</title>
      <meta property="og:title" content="SearchCast-01" />
      <meta property="og:image" content="${initialImageUrl}" /> 
      <meta property="fc:frame" content="vNext" />
      <meta property="fc:frame:image" content="${initialImageUrl}" />
      <meta property="fc:frame:image:aspect_ratio" content="1.91:1" />
      <meta property="fc:frame:input:text" content="Enter search term..." />
      <meta property="fc:frame:button:1" content="Search 🔍" />
      <meta property="fc:frame:button:1:action" content="post" />
      <meta property="fc:frame:button:2" content="Profile: ${FARCASTER_ID}" />
      <meta property="fc:frame:button:2:action" content="link" />
      <meta property="fc:frame:button:2:target" content="${FARCASTER_PROFILE_URL}" />
      <meta property="fc:frame:post_url" content="${APP_URL}/api" />
    </head>
    <body>
      <h1>SearchCast-01 Frame</h1>
      <p>Welcome to SearchCast-01. Cast this URL in a Farcaster client to use the frame.</p>
      <p>Or, paste this URL into a Farcaster frame validator.</p>
      <p>Your frame should show an input field and two buttons. The initial image is your app icon.</p>
      <img src="${initialImageUrl}" alt="Initial Frame Image" />
    </body>
    </html>
    `;
    res.setHeader('Content-Type', 'text/html');
    res.status(200).send(htmlResponse);
});


// Vercel needs us to export the app for serverless deployment
module.exports = app;